### ISSUE TITLE
Make design decision on how to inform people about the Dataverse-DASH integration

### ISSUE THREAD

**Issue by qqmyers** [harvard-lts/dspace-angular#7] opened 2022-03-08 13:39 UTC
per discussion around Miro board

**Comment by awoods** [comment] 2022-03-23 01:29
Duplicate of: https://app.zenhub.com/workspaces/hdc-62163f60fb08c60011fa4795/issues/harvard-lts/hdc/49

**Comment by awoods** [comment] 2022-03-27 20:21
@wwelling : Is this ticket not a duplicate?

**Closed** 2022-03-30 16:15 UTC
Labels: hdc, 3b

**Comment by wwelling** [comment] 2022-03-30 16:16
@awoods was not intentional to reopen this issue. Not really sure how it happened.
